# Numpy

Numpy is a library that provides support for large, homogeneous, multi-dimentional arrays and matrices.

In [2]:
import numpy as np

## Creating Arrays in Numpy
### Creating an array from a list

In [3]:
list1=[10,20,30]
list1

[10, 20, 30]

In [4]:
arr1=np.array(list1)
arr1

array([10, 20, 30])

In [5]:
type(arr1)

numpy.ndarray

### Create an array from range

Difference between array and arange is that array takes in a list and turns it into an array, whereas arage creates an array from a range of numbers

In [7]:
arr2=np.arange(10,20,1) # (start,stop,)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multi-dimentional arrays

### Combining 2 lists

When we combine arrays, we add a dimension. Combining two arrays gives 2D.
This creats a matrix for us on which we can perform matrix operations.

In [9]:
#lets create a new list to join onto the first list
list2=[40,50,60]
#join list
list3=[list1,list2]
#create array
arr3=np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
#find the shape
# 2d array with 2 rows and 3 columns
arr3.shape

(2, 3)

### 3D arrays

In [11]:
arr3dim=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [12]:
arr3dim.shape

(2, 2, 3)

## Using arrays and scalars
Numpy arrays (or ndarray) allow us to perform matrix operations.

In [13]:
#for exmaple, we can use simple multiplication
arr3dim*3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

Multiplication of array is scalar multiplication on matrix. Doing this on list, it is just repeating.

In [22]:
#we can multiply matricies (this is the dot product of vectors)
arr11=np.array(list2)
arr11

array([40, 50, 60])

In [17]:
arr1*arr11

array([ 400, 1000, 1800])

### It is possible to multiply arrays of different dimentions but same shape


In [23]:
arr1*arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

### Task

In [36]:
#1d array with 12 elements:
task1=np.arange(0,12,1)
task1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
#2d array with size (2,4):
l1=[1,2,3,4]
l2=[2,3,4,5]
l3=[3,4,5,6]
task2=np.array([l1,l2,l3])
task2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [34]:
#3d array with shape (2,5,4)
l4=[4,5,6,7]
l5=[5,6,7,8]
arrr1=[l1,l2,l3,l4,l5]
arrr2=[l5,l4,l3,l2,l1]
task3=np.array([arrr1,arrr2])
task3

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [4, 5, 6, 7],
        [3, 4, 5, 6],
        [2, 3, 4, 5],
        [1, 2, 3, 4]]])

## Accessing values

Lets take arr3 as our example, this was a 2d array.

In [40]:
#How to access 60
int(arr3[1][2])

60

In [41]:
#or
int(arr3[1,2])

60

In [42]:
#how to get bottom row
arr3[1]

array([40, 50, 60])

In [45]:
#how to get the last COLUMN
arr3[:,2]

array([30, 60])

## Stats functions

In [47]:
#sum of values
int(arr3.sum())

210

In [49]:
#sum of columns
arr3.sum(0)

array([50, 70, 90])

In [50]:
#sum or all rows
arr3.sum(1)

array([ 60, 150])

In [52]:
#mean of all values
arr3.mean()

np.float64(35.0)

In [63]:
#standard deviation of all values
arr3.std()

np.float64(17.07825127659933)

In [62]:
#variance of all values
arr3.var()

np.float64(291.6666666666667)

In [61]:
#min of all values
arr3.min()

np.int64(10)

In [60]:
#max of all values
arr3.max()

np.int64(60)

## Iterating through arrays
Simpliest is a loop

In [64]:
for x in arr1:
    print(x)

10
20
30


In [68]:
#For an n-dimentional
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [70]:
#another way! nditer
#tends to be much cleaner than nested loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


### Saving and uploading in numpy

In [71]:
#save array as file
np.save("new",arr3)

In [72]:
#load the file
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [74]:
#save as txt
np.savetxt("new.txt",arr3,delimiter=",")

In [75]:
#load as txt
np.loadtxt("new.txt",delimiter=",")

array([[10., 20., 30.],
       [40., 50., 60.]])