# Numpy

Numpy is a library that provides support for large, homogeneous, multi-dimentional arrays and matrices.

In [2]:
import numpy as np

## Creating Arrays in Numpy
### Creating an array from a list

In [3]:
list1=[10,20,30]
list1

[10, 20, 30]

In [4]:
arr1=np.array(list1)
arr1

array([10, 20, 30])

In [5]:
type(arr1)

numpy.ndarray

### Create an array from range

Difference between array and arange is that array takes in a list and turns it into an array, whereas arage creates an array from a range of numbers

In [7]:
arr2=np.arange(10,20,1) # (start,stop,)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multi-dimentional arrays

### Combining 2 lists

When we combine arrays, we add a dimension. Combining two arrays gives 2D.
This creats a matrix for us on which we can perform matrix operations.

In [9]:
#lets create a new list to join onto the first list
list2=[40,50,60]
#join list
list3=[list1,list2]
#create array
arr3=np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
#find the shape
# 2d array with 2 rows and 3 columns
arr3.shape

(2, 3)

### 3D arrays